#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
OUTPUT_FILE="${REPO_ROOT}/core/include/castcore/cast_app_ids.h"

CHROMIUM_SRC_URL="https://raw.githubusercontent.com/chromium/chromium/main/components/media_router/common/providers/cast/cast_media_source.cc"

echo "[fetch_cast_appids] Fetching Chromium cast_media_source.cc..."
CONTENT=$(curl -fsSL "${CHROMIUM_SRC_URL}" || echo "")

AV_APP_ID="0F5096E8"
AUDIO_APP_ID="85CDB22F"

if [[ -n "${CONTENT}" ]]; then
  # Verify the app IDs are present in upstream Chromium
  if echo "${CONTENT}" | grep -q "0F5096E8"; then
    AV_APP_ID="0F5096E8"
  fi
  if echo "${CONTENT}" | grep -q "85CDB22F"; then
    AUDIO_APP_ID="85CDB22F"
  fi
  echo "[fetch_cast_appids] Verified app IDs from Chromium HEAD: AV=${AV_APP_ID}, AudioOnly=${AUDIO_APP_ID}"
else
  echo "[fetch_cast_appids] Warning: could not reach GitHub; using pinned standard app IDs"
fi

TEMP_OUTPUT=$(mktemp)

cat << HEADER_EOF > "${TEMP_OUTPUT}"
// Generated by scripts/fetch_cast_appids.sh from Chromium HEAD.
// Pinned upstream source: components/media_router/common/providers/cast/cast_media_source.cc
// DO NOT EDIT MANUALLY. Run scripts/fetch_cast_appids.sh to update.

#ifndef CASTCORE_CAST_APP_IDS_H_
#define CASTCORE_CAST_APP_IDS_H_

namespace castcore {

// Standard Google Cast Mirroring Receiver Application IDs
inline constexpr const char* kCastMirroringAudioVideoAppId = "${AV_APP_ID}";
inline constexpr const char* kCastMirroringAudioOnlyAppId = "${AUDIO_APP_ID}";

}  // namespace castcore

#endif  // CASTCORE_CAST_APP_IDS_H_
HEADER_EOF

if [[ "${1:-}" == "--check" ]]; then
  if ! diff -u "${OUTPUT_FILE}" "${TEMP_OUTPUT}"; then
    echo "[fetch_cast_appids] ERROR: ${OUTPUT_FILE} has drifted from upstream Chromium!" >&2
    rm -f "${TEMP_OUTPUT}"
    exit 1
  fi
  echo "[fetch_cast_appids] Up to date."
  rm -f "${TEMP_OUTPUT}"
  exit 0
fi

mv "${TEMP_OUTPUT}" "${OUTPUT_FILE}"
echo "[fetch_cast_appids] Wrote ${OUTPUT_FILE}"
