// Generated by scripts/fetch_cast_appids.sh from Chromium HEAD.
// Pinned upstream source: components/media_router/common/providers/cast/cast_media_source.cc
// DO NOT EDIT MANUALLY. Run scripts/fetch_cast_appids.sh to update.

#ifndef CASTCORE_CAST_APP_IDS_H_
#define CASTCORE_CAST_APP_IDS_H_

namespace castcore {

// Standard Google Cast Mirroring Receiver Application IDs
inline constexpr const char* kCastMirroringAudioVideoAppId = "0F5096E8";
inline constexpr const char* kCastMirroringAudioOnlyAppId = "85CDB22F";

}  // namespace castcore

#endif  // CASTCORE_CAST_APP_IDS_H_
